/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/183evphyHdi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { Archivo } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/Input"
import { Button } from "@/components/ui/Button"
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/Collapsible"
import { JSX, SVGProps } from "react"
import { AppBar } from "./AppBar"
import { UserIcon, CalendarDaysIcon, ChevronDownIcon } from "./ui/Icons"
import { Post } from "./Post"

export const Layout: React.FC = () => (
  <div key="1" className="flex flex-col min-h-screen bg-[#14181d]">
    <AppBar />
    <main className="container mx-auto mt-32 max-w-5xl px-4 md:px-6">
      <div className="grid gap-6">
        <Post title="Minecraft Anticheats Explained" author="coEthaniccc" content="Over the last few years, I've been studying the MCPE Protocol as well as MCBE documentation for developing anticheats in MCBE. I'd like to share some knowledge on how internally MCBE handles server-authoritative movement and among other things that are important to anticheats." when="1 day ago" />
      </div>
    </main>
  </div>
)
